var data = [
    { age: 'teenager', category: 'sports ', visitor: 45 },
{ age: 'adult', category: 'politics', visitor: 49 },
{ age: 'teenager', category: 'eductaion', visitor: 68 },
{ age: 'adult', category: 'sports ', visitor: 99 },
{ age: 'adult', category: 'sports ', visitor: 67 },
{ age: 'teenager', category: 'politics', visitor: 38 },
{ age: 'adult', category: 'movie', visitor: 50 },
{ age: 'teenager', category: 'movie', visitor: 62 },
{ age: 'adult', category: 'sports ', visitor: 58 },
{ age: 'adult', category: 'sports ', visitor: 55 },
{ age: 'teenager', category: 'movie', visitor: 53 },
{ age: 'adult', category: 'eductaion', visitor: 63 },
{ age: 'adult', category: 'sports ', visitor: 54 },
{ age: 'adult', category: 'news', visitor: 54 },
{ age: 'adult', category: 'politics', visitor: 60 },
{ age: 'teenager', category: 'politics', visitor: 76 },
{ age: 'teenager', category: 'eductaion', visitor: 55 },
{ age: 'teenager', category: 'sports ', visitor: 42 },
{ age: 'teenager', category: 'eductaion', visitor: 69 },
{ age: 'adult', category: 'politics', visitor: 12 },
{ age: 'teenager', category: 'eductaion', visitor: 71 },
{ age: 'adult', category: 'sports ', visitor: 35 },
{ age: 'teenager', category: 'sports ', visitor: 88 },
{ age: 'adult', category: 'movie', visitor: 67 },
{ age: 'teenager', category: 'news', visitor: 56 },
{ age: 'adult', category: 'politics', visitor: 81 },
{ age: 'teenager', category: 'news', visitor: 78 },
{ age: 'adult', category: 'politics', visitor: 97 },
{ age: 'teenager', category: 'news', visitor: 10 },
{ age: 'teenager', category: 'sports ', visitor: 50 },
{ age: 'teenager', category: 'eductaion', visitor: 3 },
{ age: 'adult', category: 'politics', visitor: 7 },
{ age: 'adult', category: 'eductaion', visitor: 2 },
{ age: 'adult', category: 'movie', visitor: 53 },
{ age: 'adult', category: 'news', visitor: 80 },
{ age: 'teenager', category: 'sports ', visitor: 38 },
{ age: 'teenager', category: 'sports ', visitor: 31 },
{ age: 'teenager', category: 'eductaion', visitor: 27 },
{ age: 'teenager', category: 'news', visitor: 43 },
{ age: 'adult', category: 'sports ', visitor: 80 },
{ age: 'adult', category: 'news', visitor: 80 },
{ age: 'teenager', category: 'politics', visitor: 86 },
{ age: 'teenager', category: 'politics', visitor: 32 },
{ age: 'teenager', category: 'politics', visitor: 73 },
{ age: 'adult', category: 'news', visitor: 32 },
{ age: 'adult', category: 'politics', visitor: 22 },
{ age: 'adult', category: 'politics', visitor: 14 },
{ age: 'teenager', category: 'eductaion', visitor: 22 },
{ age: 'adult', category: 'news', visitor: 37 },
{ age: 'teenager', category: 'news', visitor: 12 },
{ age: 'adult', category: 'eductaion', visitor: 43 },
{ age: 'adult', category: 'eductaion', visitor: 95 },
{ age: 'teenager', category: 'news', visitor: 44 },
{ age: 'adult', category: 'movie', visitor: 81 },
{ age: 'teenager', category: 'eductaion', visitor: 84 },
{ age: 'adult', category: 'eductaion', visitor: 77 },
{ age: 'adult', category: 'sports ', visitor: 13 },
{ age: 'adult', category: 'movie', visitor: 5 },
{ age: 'adult', category: 'eductaion', visitor: 1 },
{ age: 'teenager', category: 'eductaion', visitor: 80 },
{ age: 'adult', category: 'politics', visitor: 69 },
{ age: 'teenager', category: 'politics', visitor: 0 },
{ age: 'adult', category: 'eductaion', visitor: 93 },
{ age: 'adult', category: 'eductaion', visitor: 2 },
{ age: 'adult', category: 'politics', visitor: 40 },
{ age: 'adult', category: 'sports ', visitor: 75 },
{ age: 'teenager', category: 'news', visitor: 5 },
{ age: 'adult', category: 'politics', visitor: 89 },
{ age: 'adult', category: 'news', visitor: 43 },
{ age: 'adult', category: 'eductaion', visitor: 71 },
{ age: 'teenager', category: 'news', visitor: 1 },
{ age: 'teenager', category: 'politics', visitor: 12 },
{ age: 'teenager', category: 'sports ', visitor: 81 },
{ age: 'teenager', category: 'news', visitor: 86 },
{ age: 'adult', category: 'movie', visitor: 66 },
{ age: 'teenager', category: 'sports ', visitor: 4 },
{ age: 'adult', category: 'news', visitor: 57 },
{ age: 'teenager', category: 'movie', visitor: 65 },
{ age: 'adult', category: 'eductaion', visitor: 54 },
{ age: 'adult', category: 'movie', visitor: 24 },
{ age: 'adult', category: 'politics', visitor: 26 },
{ age: 'adult', category: 'politics', visitor: 80 },
{ age: 'adult', category: 'movie', visitor: 76 },
{ age: 'adult', category: 'sports ', visitor: 74 },
{ age: 'teenager', category: 'news', visitor: 92 },
{ age: 'teenager', category: 'news', visitor: 75 },
{ age: 'adult', category: 'news', visitor: 2 },
{ age: 'adult', category: 'movie', visitor: 83 },
{ age: 'teenager', category: 'eductaion', visitor: 1 },
{ age: 'teenager', category: 'politics', visitor: 89 },
{ age: 'teenager', category: 'politics', visitor: 40 },
{ age: 'teenager', category: 'sports ', visitor: 49 },
{ age: 'adult', category: 'sports ', visitor: 38 },
{ age: 'teenager', category: 'eductaion', visitor: 41 },
{ age: 'adult', category: 'politics', visitor: 63 },
{ age: 'adult', category: 'sports ', visitor: 49 },
{ age: 'adult', category: 'politics', visitor: 4 },
{ age: 'adult', category: 'movie', visitor: 54 },
{ age: 'teenager', category: 'eductaion', visitor: 12 },
{ age: 'adult', category: 'sports ', visitor: 89 }]

// var ans = { movie: a1[], news: a2[], education: a3[], sports: a4[], politics: a5[] }

let x = age.count()
console.log(x);